import { User, Center, Session, StudentSessionEnrollment, Homework, Exam, MaterialItem, TeacherSettlement, Employee, PayrollRecord, ExpenseRecord, TeacherNote, NotificationItem } from '../types';

export const DEMO_USERS: Record<string, User> = {
  student: {
    id: 'user_student_1',
    name: 'Ahmed Mohamed',
    nameAr: 'أحمد محمد',
    email: 'student@kayedu.demo',
    phone: '+20 101 234 5678',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    centerIds: ['center_60', 'center_modern', 'center_kayedu'],
    primaryCenterId: 'center_60',
    grade: 'Grade 11 (2nd Secondary)',
    educationSystem: 'Thanaweya Amma',
    status: 'active',
    createdAt: '2025-01-15',
  },
  teacher: {
    id: 'user_teacher_1',
    name: 'Mr. Ahmed Hassan',
    nameAr: 'أ. أحمد حسن',
    email: 'teacher@kayedu.demo',
    phone: '+20 102 345 6789',
    role: 'teacher',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    centerIds: ['center_60', 'center_modern', 'center_kayedu'],
    primaryCenterId: 'center_60',
    subjects: ['Physics', 'Advanced Mechanics'],
    grades: ['Grade 10', 'Grade 11', 'Grade 12'],
    bio: '14+ years coaching high school physics across Center 60 and Center Modern. Specialist in electricity and mechanics with top Thanaweya rankings.',
    rating: 4.8,
    status: 'active',
    createdAt: '2024-08-01',
  },
  parent: {
    id: 'user_parent_1',
    name: 'Mohamed Taha (Father)',
    nameAr: 'محمد طه (ولي أمر)',
    email: 'parent@kayedu.demo',
    phone: '+20 100 987 6543',
    role: 'parent',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    centerIds: ['center_60', 'center_modern', 'center_kayedu'],
    status: 'active',
    createdAt: '2025-01-10',
  },
  center_owner: {
    id: 'user_owner_1',
    name: 'Eng. Mahmoud El-Kady',
    nameAr: 'م. محمود القاضي',
    email: 'owner@kayedu.demo',
    phone: '+20 111 222 3344',
    role: 'center_owner',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    centerIds: ['center_60', 'center_modern'],
    primaryCenterId: 'center_60',
    status: 'active',
    createdAt: '2024-01-01',
  },
  center_staff: {
    id: 'user_staff_1',
    name: 'Nouran Samir',
    nameAr: 'نوران سمير (موظفة استقبال)',
    email: 'reception@kayedu.demo',
    phone: '+20 122 333 4455',
    role: 'center_staff',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    centerIds: ['center_60', 'center_modern'],
    primaryCenterId: 'center_60',
    status: 'active',
    createdAt: '2024-06-15',
  },
  super_admin: {
    id: 'user_admin_1',
    name: 'Karim Fouad (Executive)',
    nameAr: 'كريم فؤاد (إدارة المنصة)',
    email: 'admin@kayedu.demo',
    phone: '+20 100 000 0001',
    role: 'super_admin',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: '2023-01-01',
  },
};

export const INITIAL_CENTERS: Center[] = [
  {
    id: 'center_60',
    name: 'Center 60',
    nameAr: 'سنتر 60',
    code: 'CTR-60',
    city: 'Cairo',
    district: 'Nasr City',
    address: '60 Abbas El-Akkad St., Nasr City, Cairo',
    phone: '+20 2 2260 6060',
    branches: [
      { id: 'br_60_nasr', name: 'Nasr City Main Branch', nameAr: 'فرع مدينة نصر الرئيسي' },
      { id: 'br_60_tagamoa', name: '5th Settlement Branch', nameAr: 'فرع التجمع الخامس' }
    ],
    onlinePaymentsEnabled: true,
    paymentMethods: ['card', 'wallet', 'cash'],
    subscriptionStatus: 'active',
    subscriptionPlan: 'Enterprise Tier',
    isFoundingCenter: true,
  },
  {
    id: 'center_modern',
    name: 'Center Modern',
    nameAr: 'سنتر مودرن',
    code: 'CTR-MOD',
    city: 'Giza / Cairo',
    district: 'Mohandessin',
    address: '15 Syria Street, Mohandessin, Giza',
    phone: '+20 2 3748 8888',
    branches: [
      { id: 'br_mod_mohandessin', name: 'Mohandessin Main Branch', nameAr: 'فرع المهندسين الرئيسي' },
      { id: 'br_mod_dokki', name: 'Dokki Branch', nameAr: 'فرع الدقي' }
    ],
    onlinePaymentsEnabled: true,
    paymentMethods: ['card', 'wallet', 'cash'],
    subscriptionStatus: 'active',
    subscriptionPlan: 'Enterprise Tier',
    isFoundingCenter: true,
  },
  {
    id: 'center_kayedu',
    name: 'Center 60 (Dokki)',
    nameAr: 'سنتر 60 (فرع الدقي)',
    code: 'CTR-60-DOK',
    city: 'Giza',
    district: 'Dokki',
    address: '14 Al-Mesaha Square, Dokki',
    phone: '+20 2 3761 0000',
    branches: [
      { id: 'br_dokki', name: 'Dokki Main Branch', nameAr: 'فرع الدقي الرئيسي' },
      { id: 'br_mohandessin', name: 'Mohandessin Branch', nameAr: 'فرع المهندسين' }
    ],
    onlinePaymentsEnabled: true,
    paymentMethods: ['card', 'wallet', 'cash'],
    subscriptionStatus: 'active',
    subscriptionPlan: 'Enterprise Tier',
    isFoundingCenter: true,
  },
  {
    id: 'center_future',
    name: 'Future Academy (Center 60 Partner)',
    nameAr: 'سنتر أكاديمية المستقبل (شريك سنتر 60)',
    code: 'FUT-02',
    city: 'Cairo',
    district: 'Nasr City',
    address: '88 Makram Ebeid St., Nasr City',
    phone: '+20 2 2270 5555',
    branches: [
      { id: 'br_nasrcity', name: 'Nasr City Branch', nameAr: 'فرع مدينة نصر' }
    ],
    onlinePaymentsEnabled: true,
    paymentMethods: ['card', 'wallet', 'cash'],
    subscriptionStatus: 'active',
    subscriptionPlan: 'Standard Growth',
    isFoundingCenter: false,
  }
];

export const INITIAL_TEACHERS = [
  {
    userId: 'user_teacher_1',
    name: 'Mr. Ahmed Hassan',
    nameAr: 'أ. أحمد حسن',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    title: 'Senior Physics Specialist',
    subjects: ['Physics', 'Advanced Mechanics'],
    subjectsAr: ['فيزياء', 'ميكانيكا متقدمة'],
    grades: ['Grade 10', 'Grade 11', 'Grade 12'],
    rating: 4.8,
    ratingCount: 286,
    ratingDistribution: { 5: 82, 4: 14, 3: 3, 2: 1, 1: 0 },
    experienceYears: 14,
    centerIds: ['center_60', 'center_modern', 'center_kayedu'],
    centersNames: ['Center 60', 'Center Modern'],
    bio: '14+ years coaching high school physics. Expert in simplifying Newton mechanics, thermodynamics, and electricity with top Thanaweya Amma rankings.',
    bioAr: 'أكثر من 14 عاماً في تدريس الفيزياء للثانوية العامة في سنتر 60 وسنتر مودرن، متخصص في تبسيط الكهربية والميكانيكا والفيزياء الحديثة بأعلى نسب تفوق.',
    verified: true,
    onlineAvailable: true,
  },
  {
    userId: 'user_teacher_3',
    name: 'Dr. Mona El-Sayed',
    nameAr: 'د. منى السيد',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    title: 'Ph.D. Chemistry Consultant',
    subjects: ['Chemistry'],
    subjectsAr: ['كيمياء'],
    grades: ['Grade 10', 'Grade 11', 'Grade 12'],
    rating: 4.9,
    ratingCount: 342,
    ratingDistribution: { 5: 90, 4: 8, 3: 1, 2: 1, 1: 0 },
    experienceYears: 16,
    centerIds: ['center_modern', 'center_60'],
    centersNames: ['Center Modern', 'Center 60'],
    bio: 'Former university faculty member specializing in Organic Chemistry and analytical equilibrium at Center Modern & Center 60.',
    bioAr: 'دكتوراه في الكيمياء، متخصصة في الكيمياء العضوية والاتزان الكيميائي لطلاب الثانوية العامة في سنتر مودرن وسنتر 60.',
    verified: true,
    onlineAvailable: true,
  },
  {
    userId: 'user_teacher_4',
    name: 'Mr. Tarek Mahmoud',
    nameAr: 'أ. طارق محمود',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    title: 'Pure & Applied Mathematics Master',
    subjects: ['Mathematics', 'Calculus', 'Algebra'],
    subjectsAr: ['رياضيات', 'تفاضل وتكامل', 'جبر'],
    grades: ['Grade 10', 'Grade 11', 'Grade 12'],
    rating: 4.7,
    ratingCount: 198,
    ratingDistribution: { 5: 75, 4: 18, 3: 5, 2: 1, 1: 1 },
    experienceYears: 15,
    centerIds: ['center_60', 'center_modern'],
    centersNames: ['Center 60', 'Center Modern'],
    bio: 'Mathematics Olympiad mentor and calculus expert guiding students through differentiation, integration, and solid geometry at Center 60.',
    bioAr: 'خبير الرياضيات البحتة والتطبيقية، مدرب أوائل الثانوية العامة في التفاضل والتكامل والجبر والهندسة الفراغية بسنتر 60.',
    verified: true,
    onlineAvailable: true,
  },
  {
    userId: 'user_teacher_hesham',
    name: 'Mr. Hesham Adel',
    nameAr: 'أ. هشام عادل',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    title: 'Senior Arabic Language & Rhetoric Educator',
    subjects: ['Arabic Language', 'Literature & Rhetoric'],
    subjectsAr: ['اللغة العربية', 'البلاغة والأدب والنحو'],
    grades: ['Grade 10', 'Grade 11', 'Grade 12'],
    rating: 4.9,
    ratingCount: 260,
    ratingDistribution: { 5: 88, 4: 10, 3: 2, 2: 0, 1: 0 },
    experienceYears: 18,
    centerIds: ['center_modern', 'center_60'],
    centersNames: ['Center Modern', 'Center 60'],
    bio: 'Master of Arabic grammar, rhetoric, and modern text interpretation. Renowned lecturer at Center Modern and Center 60.',
    bioAr: 'كبير معلمي اللغة العربية والبلاغة والنحو للثانوية العامة في سنتر مودرن وسنتر 60، تبسيط شامل لأدق تفاصيل النحو والقراءة المتحررة.',
    verified: true,
    onlineAvailable: true,
  },
  {
    userId: 'user_teacher_salma',
    name: 'Ms. Salma Sherif',
    nameAr: 'أ. سلمى شريف',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=200&auto=format&fit=crop&q=80',
    title: 'Biology & Geology Specialist',
    subjects: ['Biology', 'Geology'],
    subjectsAr: ['أحياء', 'جيولوجيا'],
    grades: ['Grade 11', 'Grade 12'],
    rating: 4.8,
    ratingCount: 175,
    ratingDistribution: { 5: 80, 4: 15, 3: 4, 2: 1, 1: 0 },
    experienceYears: 11,
    centerIds: ['center_60', 'center_modern'],
    centersNames: ['Center 60', 'Center Modern'],
    bio: 'Specialist in human genetics, immunology, and reproductive biology with interactive animated lectures at Center 60.',
    bioAr: 'متخصصة في الأحياء والجيولوجيا، شرح تفاعلي بالمجسمات ثلاثية الأبعاد للمناعة والوراثة الجزيئية DNA في سنتر 60.',
    verified: true,
    onlineAvailable: false,
  },
  {
    userId: 'user_teacher_shennawy',
    name: 'Mr. Mahmoud El-Shennawy',
    nameAr: 'أ. محمود الشناوي',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    title: 'Advanced English Language Coach',
    subjects: ['English Language'],
    subjectsAr: ['اللغة الإنجليزية'],
    grades: ['Grade 10', 'Grade 11', 'Grade 12'],
    rating: 4.7,
    ratingCount: 220,
    ratingDistribution: { 5: 76, 4: 19, 3: 4, 2: 1, 1: 0 },
    experienceYears: 13,
    centerIds: ['center_modern'],
    centersNames: ['Center Modern'],
    bio: 'Cambridge certified English trainer focusing on Thanaweya translation, vocabulary mastery, and essay composition at Center Modern.',
    bioAr: 'معلم أول لغة إنجليزية معتمد، تدريب مكثف على الترجمة ومهارات المقال والقصة لطلاب الثانوية في سنتر مودرن.',
    verified: true,
    onlineAvailable: true,
  }
];

export const INITIAL_SESSIONS: Session[] = [
  // --- CENTER 60 SESSIONS ---
  {
    id: 'sess_60_phy_today',
    centerId: 'center_60',
    centerName: 'Center 60',
    centerNameAr: 'سنتر 60',
    branchName: 'Nasr City Main Branch',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    teacherNameAr: 'أ. أحمد حسن',
    teacherAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    subject: 'Physics',
    subjectAr: 'فيزياء',
    grade: 'Grade 11',
    groupName: 'Center 60 Group A — Mechanics & Harmonic Motion',
    room: 'Hall 1 (Center 60)',
    date: '2026-09-08',
    startTime: '18:00',
    endTime: '20:00',
    priceEgp: 200,
    isOnline: false,
    capacity: 45,
    enrolledCount: 38,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_phy_today', // Alias for backwards compatibility
    centerId: 'center_60',
    centerName: 'Center 60',
    centerNameAr: 'سنتر 60',
    branchName: 'Nasr City Main Branch',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    teacherNameAr: 'أ. أحمد حسن',
    teacherAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    subject: 'Physics',
    subjectAr: 'فيزياء',
    grade: 'Grade 11',
    groupName: 'Group A — Mechanics & Waves',
    room: 'Hall 1 (Center 60)',
    date: '2026-09-08',
    startTime: '18:00',
    endTime: '20:00',
    priceEgp: 200,
    isOnline: false,
    capacity: 45,
    enrolledCount: 38,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_60_math_tomorrow',
    centerId: 'center_60',
    centerName: 'Center 60',
    centerNameAr: 'سنتر 60',
    branchName: 'Nasr City Main Branch',
    teacherId: 'user_teacher_4',
    teacherName: 'Mr. Tarek Mahmoud',
    teacherNameAr: 'أ. طارق محمود',
    teacherAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    subject: 'Mathematics',
    subjectAr: 'رياضيات بحتة وتفاضل',
    grade: 'Grade 12',
    groupName: 'Center 60 Thanaweya Elite — Calculus Derivatives',
    room: 'Hall 3 (Center 60)',
    date: '2026-09-09',
    startTime: '16:00',
    endTime: '18:30',
    priceEgp: 220,
    isOnline: false,
    capacity: 50,
    enrolledCount: 46,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_60_bio_sat',
    centerId: 'center_60',
    centerName: 'Center 60',
    centerNameAr: 'سنتر 60',
    branchName: '5th Settlement Branch',
    teacherId: 'user_teacher_salma',
    teacherName: 'Ms. Salma Sherif',
    teacherNameAr: 'أ. سلمى شريف',
    teacherAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=200&auto=format&fit=crop&q=80',
    subject: 'Biology',
    subjectAr: 'أحياء',
    grade: 'Grade 11',
    groupName: 'Center 60 Group B — Human Genetics & DNA',
    room: 'Hall 2 (Center 60)',
    date: '2026-09-12',
    startTime: '12:00',
    endTime: '14:00',
    priceEgp: 190,
    isOnline: false,
    capacity: 40,
    enrolledCount: 35,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_60_ar_mon',
    centerId: 'center_60',
    centerName: 'Center 60',
    centerNameAr: 'سنتر 60',
    branchName: 'Nasr City Main Branch',
    teacherId: 'user_teacher_hesham',
    teacherName: 'Mr. Hesham Adel',
    teacherNameAr: 'أ. هشام عادل',
    teacherAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    subject: 'Arabic Language',
    subjectAr: 'لغة عربية ونحو',
    grade: 'Grade 10',
    groupName: 'Center 60 Foundation — Grammar & Rhetoric',
    room: 'Hall 4 (Center 60)',
    date: '2026-09-14',
    startTime: '17:00',
    endTime: '19:00',
    priceEgp: 180,
    isOnline: false,
    capacity: 35,
    enrolledCount: 29,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_60_phy_g10',
    centerId: 'center_60',
    centerName: 'Center 60',
    centerNameAr: 'سنتر 60',
    branchName: 'Nasr City Main Branch',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    teacherNameAr: 'أ. أحمد حسن',
    teacherAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    subject: 'Physics',
    subjectAr: 'فيزياء',
    grade: 'Grade 10',
    groupName: 'Center 60 Grade 10 — Physical Measurements & Dimensional Formula',
    room: 'Hall 1 (Center 60)',
    date: '2026-09-08',
    startTime: '16:00',
    endTime: '17:45',
    priceEgp: 180,
    isOnline: false,
    capacity: 40,
    enrolledCount: 26,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_60_math_g10',
    centerId: 'center_60',
    centerName: 'Center 60',
    centerNameAr: 'سنتر 60',
    branchName: 'Nasr City Main Branch',
    teacherId: 'user_teacher_4',
    teacherName: 'Mr. Tarek Mahmoud',
    teacherNameAr: 'أ. طارق محمود',
    teacherAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    subject: 'Mathematics',
    subjectAr: 'رياضيات وجبر',
    grade: 'Grade 10',
    groupName: 'Center 60 Grade 10 — Complex Numbers & Quadratic Equations',
    room: 'Hall 3 (Center 60)',
    date: '2026-09-09',
    startTime: '15:00',
    endTime: '17:00',
    priceEgp: 190,
    isOnline: false,
    capacity: 45,
    enrolledCount: 31,
    status: 'SCHEDULED',
  },

  // --- CENTER MODERN SESSIONS ---
  {
    id: 'sess_mod_chem_today',
    centerId: 'center_modern',
    centerName: 'Center Modern',
    centerNameAr: 'سنتر مودرن',
    branchName: 'Mohandessin Main Branch',
    teacherId: 'user_teacher_3',
    teacherName: 'Dr. Mona El-Sayed',
    teacherNameAr: 'د. منى السيد',
    teacherAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    subject: 'Chemistry',
    subjectAr: 'كيمياء',
    grade: 'Grade 11',
    groupName: 'Center Modern Group Alpha — Chemical Equilibrium',
    room: 'VIP Hall A (Center Modern)',
    date: '2026-09-08',
    startTime: '15:30',
    endTime: '17:30',
    priceEgp: 220,
    isOnline: false,
    capacity: 40,
    enrolledCount: 38,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_chem_today', // Alias for backwards compatibility
    centerId: 'center_modern',
    centerName: 'Center Modern',
    centerNameAr: 'سنتر مودرن',
    branchName: 'Mohandessin Main Branch',
    teacherId: 'user_teacher_3',
    teacherName: 'Dr. Mona El-Sayed',
    teacherNameAr: 'د. منى السيد',
    teacherAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    subject: 'Chemistry',
    subjectAr: 'كيمياء',
    grade: 'Grade 11',
    groupName: 'Group B — Ionic Equilibrium',
    room: 'VIP Hall A (Center Modern)',
    date: '2026-09-08',
    startTime: '15:30',
    endTime: '17:30',
    priceEgp: 220,
    isOnline: false,
    capacity: 40,
    enrolledCount: 38,
    status: 'COMPLETED',
  },
  {
    id: 'sess_mod_eng_tomorrow',
    centerId: 'center_modern',
    centerName: 'Center Modern',
    centerNameAr: 'سنتر مودرن',
    branchName: 'Mohandessin Main Branch',
    teacherId: 'user_teacher_shennawy',
    teacherName: 'Mr. Mahmoud El-Shennawy',
    teacherNameAr: 'أ. محمود الشناوي',
    teacherAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    subject: 'English Language',
    subjectAr: 'لغة إنجليزية متقدمة',
    grade: 'Grade 12',
    groupName: 'Center Modern Thanaweya — Great Expectations & Vocab',
    room: 'Hall 5 (Center Modern)',
    date: '2026-09-09',
    startTime: '18:00',
    endTime: '20:00',
    priceEgp: 190,
    isOnline: false,
    capacity: 45,
    enrolledCount: 42,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_mod_phy_thu',
    centerId: 'center_modern',
    centerName: 'Center Modern',
    centerNameAr: 'سنتر مودرن',
    branchName: 'Dokki Branch',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    teacherNameAr: 'أ. أحمد حسن',
    teacherAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    subject: 'Physics',
    subjectAr: 'فيزياء حديثة',
    grade: 'Grade 12',
    groupName: 'Center Modern Super Group — Quantum & Dual Nature',
    room: 'Hall 1 (Center Modern)',
    date: '2026-09-10',
    startTime: '17:00',
    endTime: '19:30',
    priceEgp: 240,
    isOnline: false,
    capacity: 60,
    enrolledCount: 57,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_mod_ar_sun',
    centerId: 'center_modern',
    centerName: 'Center Modern',
    centerNameAr: 'سنتر مودرن',
    branchName: 'Mohandessin Main Branch',
    teacherId: 'user_teacher_hesham',
    teacherName: 'Mr. Hesham Adel',
    teacherNameAr: 'أ. هشام عادل',
    teacherAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    subject: 'Arabic Language',
    subjectAr: 'لغة عربية وبلاغة',
    grade: 'Grade 12',
    groupName: 'Center Modern Thanaweya — Rhetoric & Text Analysis',
    room: 'Main Amphitheater (Center Modern)',
    date: '2026-09-13',
    startTime: '16:30',
    endTime: '19:00',
    priceEgp: 210,
    isOnline: false,
    capacity: 70,
    enrolledCount: 65,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_mod_chem_g10',
    centerId: 'center_modern',
    centerName: 'Center Modern',
    centerNameAr: 'سنتر مودرن',
    branchName: 'Mohandessin Main Branch',
    teacherId: 'user_teacher_3',
    teacherName: 'Dr. Mona El-Sayed',
    teacherNameAr: 'د. منى السيد',
    teacherAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    subject: 'Chemistry',
    subjectAr: 'كيمياء',
    grade: 'Grade 10',
    groupName: 'Center Modern Grade 10 — Chemistry Central Science & Nanotechnology',
    room: 'VIP Hall A (Center Modern)',
    date: '2026-09-08',
    startTime: '18:00',
    endTime: '20:00',
    priceEgp: 185,
    isOnline: false,
    capacity: 38,
    enrolledCount: 24,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_mod_eng_g10',
    centerId: 'center_modern',
    centerName: 'Center Modern',
    centerNameAr: 'سنتر مودرن',
    branchName: 'Mohandessin Main Branch',
    teacherId: 'user_teacher_shennawy',
    teacherName: 'Mr. Mahmoud El-Shennawy',
    teacherNameAr: 'أ. محمود الشناوي',
    teacherAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    subject: 'English Language',
    subjectAr: 'لغة إنجليزية',
    grade: 'Grade 10',
    groupName: 'Center Modern Grade 10 — Unit 1 Getting Away & Grammar',
    room: 'Hall 5 (Center Modern)',
    date: '2026-09-10',
    startTime: '16:00',
    endTime: '18:00',
    priceEgp: 175,
    isOnline: false,
    capacity: 40,
    enrolledCount: 27,
    status: 'SCHEDULED',
  }
];

export const INITIAL_ENROLLMENTS: StudentSessionEnrollment[] = [
  {
    id: 'enr_60_phy',
    sessionId: 'sess_60_phy_today',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    studentCode: 'ST-001245',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    paymentStatus: 'PENDING',
    reservationStatus: 'CONFIRMED',
  },
  {
    id: 'enr_1', // Alias
    sessionId: 'sess_phy_today',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    studentCode: 'ST-001245',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    paymentStatus: 'PENDING',
    reservationStatus: 'CONFIRMED',
  },
  {
    id: 'enr_mod_chem',
    sessionId: 'sess_mod_chem_today',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    studentCode: 'ST-001245',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    paymentStatus: 'PAID',
    paymentMethod: 'online_card',
    paidAmount: 220,
    paidAt: '2026-09-08 11:30',
    receiptNumber: 'REC-MOD-20260908-044',
    attendanceStatus: 'PRESENT',
    attendanceTime: '15:25',
    reservationStatus: 'CONFIRMED',
  },
  {
    id: 'enr_60_math',
    sessionId: 'sess_60_math_tomorrow',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    studentCode: 'ST-001245',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    paymentStatus: 'PAID',
    paymentMethod: 'digital_wallet',
    paidAmount: 220,
    paidAt: '2026-09-07 19:15',
    receiptNumber: 'REC-60-20260907-088',
    reservationStatus: 'CONFIRMED',
  },
  {
    id: 'enr_mod_eng',
    sessionId: 'sess_mod_eng_tomorrow',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    studentCode: 'ST-001245',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    paymentStatus: 'PENDING',
    reservationStatus: 'CONFIRMED',
  },
  {
    id: 'enr_mod_phy',
    sessionId: 'sess_mod_phy_thu',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    studentCode: 'ST-001245',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    paymentStatus: 'PAID',
    paymentMethod: 'online_card',
    paidAmount: 240,
    paidAt: '2026-09-06 14:00',
    receiptNumber: 'REC-MOD-20260906-012',
    reservationStatus: 'CONFIRMED',
  },
  {
    id: 'enr_60_bio',
    sessionId: 'sess_60_bio_sat',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    studentCode: 'ST-001245',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    paymentStatus: 'PAID',
    paymentMethod: 'center_cash',
    paidAmount: 190,
    paidAt: '2026-09-05 16:30',
    receiptNumber: 'REC-60-20260905-099',
    reservationStatus: 'CONFIRMED',
  }
];

export const INITIAL_HOMEWORK: Homework[] = [
  // --- CENTER 60 HOMEWORK ---
  {
    id: 'hw_60_phy',
    sessionId: 'sess_60_phy_today',
    teacherId: 'user_teacher_1',
    centerId: 'center_60',
    subject: 'Physics',
    grade: 'Grade 11',
    title: 'Center 60: Harmonic Motion & Wave Interference Problem Set',
    titleAr: 'سنتر 60: مسائل الحركة التوافقية البسيطة وتداخل الأمواج',
    instructions: 'Complete all 5 problems showing step-by-step physical calculations. Center 60 hall 1 revision.',
    dueDate: '2026-09-12 23:59',
    assignedDate: '2026-09-08',
    status: 'PUBLISHED',
    questionsCount: 5,
    questions: [
      {
        id: 'q1',
        type: 'mcq',
        prompt: 'If the frequency of a vibrating pendulum is doubled, its periodic time will:',
        choices: ['Double', 'Halve', 'Remain unchanged', 'Quadruple'],
        correctAnswer: 'Halve',
        points: 2
      },
      {
        id: 'q2',
        type: 'true_false',
        prompt: 'Electromagnetic waves require a material medium to propagate through space.',
        choices: ['True', 'False'],
        correctAnswer: 'False',
        points: 2
      },
      {
        id: 'q3',
        type: 'short_answer',
        prompt: 'State the relationship between wave speed (v), frequency (f), and wavelength (lambda).',
        correctAnswer: 'v = f * lambda',
        points: 3
      }
    ]
  },
  {
    id: 'hw_60_math',
    sessionId: 'sess_60_math_tomorrow',
    teacherId: 'user_teacher_4',
    centerId: 'center_60',
    subject: 'Mathematics',
    grade: 'Grade 12',
    title: 'Center 60: Calculus Derivatives & Chain Rule Master Set',
    titleAr: 'سنتر 60: تفاضل الدوال المثلثية وقاعدة السلسلة',
    instructions: 'Solve high-yield Thanaweya Amma questions from Center 60 problem booklet.',
    dueDate: '2026-09-13 22:00',
    assignedDate: '2026-09-08',
    status: 'PUBLISHED',
    questionsCount: 6,
  },
  {
    id: 'hw_60_bio',
    sessionId: 'sess_60_bio_sat',
    teacherId: 'user_teacher_salma',
    centerId: 'center_60',
    subject: 'Biology',
    grade: 'Grade 11',
    title: 'Center 60: Human Genetics & DNA Structure Worksheet',
    titleAr: 'سنتر 60: ورقة عمل الوراثة الجزيئية وتركيب الحمض النووي',
    instructions: 'Analyze cross-over diagrams and genetic pedigree trees attached to Center 60 portal.',
    dueDate: '2026-09-14 20:00',
    assignedDate: '2026-09-08',
    status: 'PUBLISHED',
    questionsCount: 4,
  },

  // --- CENTER MODERN HOMEWORK ---
  {
    id: 'hw_mod_chem',
    sessionId: 'sess_mod_chem_today',
    teacherId: 'user_teacher_3',
    centerId: 'center_modern',
    subject: 'Chemistry',
    grade: 'Grade 11',
    title: 'Center Modern: Chemical Equilibrium & Le Chatelier Applications',
    titleAr: 'سنتر مودرن: تطبيقات قاعدة لوشاتيليه في الاتزان الكيميائي',
    instructions: 'Analyze the reaction quotient under temperature and pressure shifts at Center Modern VIP Lab.',
    dueDate: '2026-09-12 20:00',
    assignedDate: '2026-09-08',
    status: 'PUBLISHED',
    questionsCount: 4,
    questions: [
      {
        id: 'cq1',
        type: 'mcq',
        prompt: 'Increasing pressure on an equilibrium gas mixture shifts the reaction toward:',
        choices: ['Side with fewer gas moles', 'Side with more gas moles', 'Does not shift', 'Endothermic side'],
        correctAnswer: 'Side with fewer gas moles',
        points: 3
      },
      {
        id: 'cq2',
        type: 'true_false',
        prompt: 'Adding a catalyst shifts the position of chemical equilibrium to the right.',
        choices: ['True', 'False'],
        correctAnswer: 'False',
        points: 2
      }
    ]
  },
  {
    id: 'hw_mod_eng',
    sessionId: 'sess_mod_eng_tomorrow',
    teacherId: 'user_teacher_shennawy',
    centerId: 'center_modern',
    subject: 'English Language',
    grade: 'Grade 12',
    title: 'Center Modern: Great Expectations Chapters 1-3 & Essay Practice',
    titleAr: 'سنتر مودرن: قصة الآمال الكبرى وتطبيقات المقال والترجمة',
    instructions: 'Write a 150-word synthesis essay and answer analytical character questions for Center Modern class.',
    dueDate: '2026-09-14 23:59',
    assignedDate: '2026-09-08',
    status: 'PUBLISHED',
    questionsCount: 5,
  },
  {
    id: 'hw_mod_ar',
    sessionId: 'sess_mod_ar_sun',
    teacherId: 'user_teacher_hesham',
    centerId: 'center_modern',
    subject: 'Arabic Language',
    grade: 'Grade 12',
    title: 'Center Modern: Comprehensive Nahw & Balagha Drills',
    titleAr: 'سنتر مودرن: تدريبات النحو الشاملة وإعراب الشواهد الشعرية',
    instructions: 'Solve 20 Thanaweya multiple choice questions on derivative nouns and rhetorical metaphors.',
    dueDate: '2026-09-15 21:00',
    assignedDate: '2026-09-08',
    status: 'PUBLISHED',
    questionsCount: 8,
  }
];

export const INITIAL_EXAMS: Exam[] = [
  // --- CENTER 60 EXAMS ---
  {
    id: 'exam_60_phy',
    centerId: 'center_60',
    teacherId: 'user_teacher_1',
    subject: 'Physics',
    grade: 'Grade 11',
    title: 'Center 60 Monthly Physics Assessment — Mechanics',
    durationMinutes: 45,
    date: '2026-09-15',
    startTime: '18:00',
    totalPoints: 30,
    status: 'OPEN',
    questions: [
      {
        id: 'eq1',
        questionNumber: 1,
        type: 'mcq',
        prompt: 'A body moves in circular motion with constant speed. Which of the following is correct?',
        choices: [
          'Its acceleration is zero',
          'Its velocity vector is constant',
          'Centripetal acceleration is directed toward the circle center',
          'Linear speed is proportional to period'
        ],
        correctAnswer: 'Centripetal acceleration is directed toward the circle center',
        points: 5
      },
      {
        id: 'eq2',
        questionNumber: 2,
        type: 'true_false',
        prompt: 'Gravitational acceleration remains identical regardless of altitude above Earth.',
        choices: ['True', 'False'],
        correctAnswer: 'False',
        points: 5
      },
      {
        id: 'eq3',
        questionNumber: 3,
        type: 'mcq',
        prompt: 'What happens to the kinetic energy of a car if its speed is tripled?',
        choices: ['Triples (3x)', 'Increases to 6x', 'Increases to 9x', 'Remains the same'],
        correctAnswer: 'Increases to 9x',
        points: 5
      }
    ]
  },
  {
    id: 'exam_60_math',
    centerId: 'center_60',
    teacherId: 'user_teacher_4',
    subject: 'Mathematics',
    grade: 'Grade 12',
    title: 'Center 60 Pure Math Midterm Challenge',
    durationMinutes: 60,
    date: '2026-09-17',
    startTime: '16:00',
    totalPoints: 40,
    status: 'OPEN',
    questions: [
      {
        id: 'meq1',
        questionNumber: 1,
        type: 'mcq',
        prompt: 'The derivative of y = sin(3x^2) with respect to x is:',
        choices: ['6x * cos(3x^2)', 'cos(6x)', '6 * sin(3x^2)', '3x * cos(3x^2)'],
        correctAnswer: '6x * cos(3x^2)',
        points: 10
      }
    ]
  },

  // --- CENTER MODERN EXAMS ---
  {
    id: 'exam_mod_chem',
    centerId: 'center_modern',
    teacherId: 'user_teacher_3',
    subject: 'Chemistry',
    grade: 'Grade 11',
    title: 'Center Modern Comprehensive Chemistry Assessment',
    durationMinutes: 50,
    date: '2026-09-16',
    startTime: '15:30',
    totalPoints: 35,
    status: 'OPEN',
    questions: [
      {
        id: 'ceq1',
        questionNumber: 1,
        type: 'mcq',
        prompt: 'For an exothermic reaction at equilibrium, increasing temperature will:',
        choices: ['Decrease Kc value', 'Increase Kc value', 'Keep Kc unchanged', 'Shift reaction forward'],
        correctAnswer: 'Decrease Kc value',
        points: 10
      }
    ]
  },
  {
    id: 'exam_mod_eng',
    centerId: 'center_modern',
    teacherId: 'user_teacher_shennawy',
    subject: 'English Language',
    grade: 'Grade 12',
    title: 'Center Modern English Unit 3 Assessment',
    durationMinutes: 45,
    date: '2026-09-18',
    startTime: '18:00',
    totalPoints: 30,
    status: 'OPEN',
    questions: [
      {
        id: 'eeq1',
        questionNumber: 1,
        type: 'mcq',
        prompt: 'Choose the correct synonym for "resilient":',
        choices: ['Durable & adaptable', 'Fragile', 'Vague', 'Hesitant'],
        correctAnswer: 'Durable & adaptable',
        points: 10
      }
    ]
  }
];

export const INITIAL_MATERIALS: MaterialItem[] = [
  {
    id: 'mat_1',
    title: 'Physics Chapter 1 Summary — Vectors & Motion Notes (PDF)',
    subject: 'Physics',
    grade: 'Grade 11',
    teacherName: 'Mr. Ahmed Hassan',
    type: 'pdf',
    fileSize: '4.2 MB',
    url: '#',
    date: '2026-09-05'
  },
  {
    id: 'mat_2',
    title: 'Comprehensive Organic Chemistry Formulas & Functional Groups',
    subject: 'Chemistry',
    grade: 'Grade 11',
    teacherName: 'Dr. Mona El-Sayed',
    type: 'pdf',
    fileSize: '3.1 MB',
    url: '#',
    date: '2026-09-06'
  },
  {
    id: 'mat_3',
    title: 'Interactive 3D Wave Interference Simulation Link',
    subject: 'Physics',
    grade: 'Grade 11',
    teacherName: 'Mr. Ahmed Hassan',
    type: 'link',
    url: 'https://phet.colorado.edu/en/simulations/wave-interference',
    date: '2026-09-07'
  }
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp_1',
    centerId: 'center_kayedu',
    name: 'Nouran Samir',
    nameAr: 'نوران سمير',
    phone: '+20 122 333 4455',
    role: 'Receptionist',
    branchName: 'Dokki Main Branch',
    status: 'active',
    compensationModel: 'HYBRID',
    baseSalaryEgp: 6500,
    sessionPercentage: 2,
    eligibleSessionsThisMonth: 42,
    startDate: '2024-06-15',
  },
  {
    id: 'emp_2',
    centerId: 'center_kayedu',
    name: 'Hassan Sherif',
    nameAr: 'حسن شريف',
    phone: '+20 109 888 7766',
    role: 'Floor Supervisor',
    branchName: 'Dokki Main Branch',
    status: 'active',
    compensationModel: 'FIXED_PER_SESSION',
    baseSalaryEgp: 0,
    perSessionRateEgp: 90,
    eligibleSessionsThisMonth: 58,
    startDate: '2024-09-01',
  },
  {
    id: 'emp_3',
    centerId: 'center_kayedu',
    name: 'Marwa Zaki',
    nameAr: 'مروة زكي',
    phone: '+20 115 444 3322',
    role: 'Accountant',
    branchName: 'Dokki Main Branch',
    status: 'active',
    compensationModel: 'FIXED_SALARY',
    baseSalaryEgp: 8500,
    eligibleSessionsThisMonth: 0,
    startDate: '2024-03-01',
  }
];

export const INITIAL_PAYROLL: PayrollRecord[] = [
  {
    id: 'pay_01',
    centerId: 'center_kayedu',
    employeeId: 'emp_1',
    employeeName: 'Nouran Samir',
    role: 'Receptionist',
    period: '2026-08',
    baseSalaryEgp: 6500,
    sessionEarningsEgp: 1680,
    bonusEgp: 500,
    overtimeEgp: 350,
    deductionsEgp: 0,
    netPayEgp: 9030,
    status: 'APPROVED',
  },
  {
    id: 'pay_02',
    centerId: 'center_kayedu',
    employeeId: 'emp_2',
    employeeName: 'Hassan Sherif',
    role: 'Floor Supervisor',
    period: '2026-08',
    baseSalaryEgp: 0,
    sessionEarningsEgp: 5220,
    bonusEgp: 300,
    overtimeEgp: 0,
    deductionsEgp: 150,
    netPayEgp: 5370,
    status: 'REVIEWED',
  }
];

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: 'exp_1',
    centerId: 'center_kayedu',
    category: 'Rent',
    amountEgp: 35000,
    date: '2026-09-01',
    branch: 'Dokki Main Branch',
    description: 'Monthly facility commercial lease — Dokki 14 Al-Mesaha',
    paymentMethod: 'Bank Transfer',
    createdBy: 'Eng. Mahmoud El-Kady',
  },
  {
    id: 'exp_2',
    centerId: 'center_kayedu',
    category: 'Electricity',
    amountEgp: 6400,
    date: '2026-09-03',
    branch: 'Dokki Main Branch',
    description: 'Electricity & Air Conditioning utility bill for August',
    paymentMethod: 'Fawry Business',
    createdBy: 'Marwa Zaki',
  },
  {
    id: 'exp_3',
    centerId: 'center_kayedu',
    category: 'Internet',
    amountEgp: 2200,
    date: '2026-09-04',
    branch: 'Dokki Main Branch',
    description: 'Fiber internet 200Mbps dedicated connection',
    paymentMethod: 'Credit Card',
    createdBy: 'Marwa Zaki',
  },
  {
    id: 'exp_4',
    centerId: 'center_kayedu',
    category: 'Supplies',
    amountEgp: 4800,
    date: '2026-09-05',
    branch: 'Dokki Main Branch',
    description: 'Photocopy paper reams & white board markers for halls',
    paymentMethod: 'Cash Voucher',
    createdBy: 'Nouran Samir',
  }
];

export const INITIAL_TEACHER_SETTLEMENTS: TeacherSettlement[] = [
  {
    id: 'settle_1',
    centerId: 'center_kayedu',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    subject: 'Physics',
    period: '2026-08',
    sessionsCount: 16,
    attendedStudentsCount: 512,
    totalRevenueEgp: 102400,
    calculationRule: 'percentage_80',
    teacherShareEgp: 81920,
    centerShareEgp: 20480,
    adjustmentsEgp: 0,
    paidAmountEgp: 81920,
    status: 'PAID',
    paidAt: '2026-09-02',
  },
  {
    id: 'settle_2',
    centerId: 'center_kayedu',
    teacherId: 'user_teacher_3',
    teacherName: 'Dr. Mona El-Sayed',
    subject: 'Chemistry',
    period: '2026-08',
    sessionsCount: 14,
    attendedStudentsCount: 440,
    totalRevenueEgp: 96800,
    calculationRule: 'percentage_75',
    teacherShareEgp: 72600,
    centerShareEgp: 24200,
    adjustmentsEgp: -600,
    paidAmountEgp: 0,
    status: 'REVIEWED',
  }
];

export const INITIAL_TEACHER_NOTES: TeacherNote[] = [
  {
    id: 'note_1',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    type: 'Academic',
    visibility: 'parent_and_student',
    content: 'Demonstrated outstanding grasp of Newton third law applications in problem set 3. Recommended for Thanweya Amma honor group.',
    date: '2026-09-06',
  },
  {
    id: 'note_2',
    teacherId: 'user_teacher_3',
    teacherName: 'Dr. Mona El-Sayed',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    type: 'Follow-up',
    visibility: 'parent_only',
    content: 'Missed chemistry lab worksheet review on Tuesday. Please ensure he revises ionic reactions before the upcoming quiz.',
    date: '2026-09-07',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'user_student_1',
    type: 'class_reminder',
    title: 'Physics Class Today at 6:00 PM',
    titleAr: 'تذكير: حصة الفيزياء اليوم الساعة 6:00 مساءً',
    message: 'Mr. Ahmed Hassan in Room 4, Dokki Main Branch. Have your attendance QR ready.',
    messageAr: 'مع أ. أحمد حسن في القاعة 4، فرع الدقي. جهز رمز QR للحضور عند الاستقبال.',
    timestamp: '10 mins ago',
    read: false,
  },
  {
    id: 'notif_2',
    userId: 'user_student_1',
    type: 'homework',
    title: 'New Physics Homework Assigned',
    titleAr: 'واجب جديد: مسائل الحركة التوافقية',
    message: 'Due date: Saturday Sep 12, 11:59 PM.',
    messageAr: 'موعد التسليم الأخير: السبت 12 سبتمبر الساعة 11:59 مساءً.',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: 'notif_3',
    userId: 'user_student_1',
    type: 'exam',
    title: 'Assessment Result Published',
    titleAr: 'تم إعلان نتيجة الاختبار الأسبوعي',
    message: 'You scored 28/30 (93.3%) in Wave Mechanics.',
    messageAr: 'حصلت على 28 من 30 (93.3%) في ميكانيكا الموجات.',
    timestamp: 'Yesterday',
    read: true,
  }
];
