import { User, Center, Session, StudentSessionEnrollment, Homework, Exam, MaterialItem, TeacherSettlement, Employee, PayrollRecord, ExpenseRecord, TeacherNote, NotificationItem } from '../types';

export const DEMO_USERS: Record<string, User> = {
  student: {
    id: 'user_student_1',
    name: 'Ahmed Mohamed',
    nameAr: 'أحمد محمد',
    email: 'student@kayedu.demo',
    phone: '+20 101 234 5678',
    role: 'student',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    centerIds: ['center_kayedu', 'center_future'],
    primaryCenterId: 'center_kayedu',
    status: 'active',
    createdAt: '2025-01-15',
  },
  teacher: {
    id: 'user_teacher_1',
    name: 'Mr. Ahmed Hassan',
    nameAr: 'أ. أحمد حسن',
    email: 'teacher@kayedu.demo',
    phone: '+20 102 345 6789',
    role: 'teacher',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    centerIds: ['center_kayedu', 'center_future', 'center_elite'],
    primaryCenterId: 'center_kayedu',
    status: 'active',
    createdAt: '2024-08-01',
  },
  parent: {
    id: 'user_parent_1',
    name: 'Mohamed Taha (Father)',
    nameAr: 'محمد طه (ولي أمر)',
    email: 'parent@kayedu.demo',
    phone: '+20 100 987 6543',
    role: 'parent',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    centerIds: ['center_kayedu', 'center_future'],
    status: 'active',
    createdAt: '2025-01-10',
  },
  center_owner: {
    id: 'user_owner_1',
    name: 'Eng. Mahmoud El-Kady',
    nameAr: 'م. محمود القاضي',
    email: 'owner@kayedu.demo',
    phone: '+20 111 222 3344',
    role: 'center_owner',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    centerIds: ['center_kayedu'],
    primaryCenterId: 'center_kayedu',
    status: 'active',
    createdAt: '2024-01-01',
  },
  center_staff: {
    id: 'user_staff_1',
    name: 'Nouran Samir',
    nameAr: 'نوران سمير (موظفة استقبال)',
    email: 'reception@kayedu.demo',
    phone: '+20 122 333 4455',
    role: 'center_staff',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    centerIds: ['center_kayedu'],
    primaryCenterId: 'center_kayedu',
    status: 'active',
    createdAt: '2024-06-15',
  },
  super_admin: {
    id: 'user_admin_1',
    name: 'KAY-SOFT Executive Admin',
    nameAr: 'إدارة منصة كاي-سوفت',
    email: 'admin@kayedu.demo',
    phone: '+20 100 000 0001',
    role: 'super_admin',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: '2023-01-01',
  },
};

export const INITIAL_CENTERS: Center[] = [
  {
    id: 'center_kayedu',
    name: 'KAYEDU Demo Center',
    nameAr: 'سنتر كاي إديو النموذجي',
    code: 'KAY-01',
    city: 'Giza',
    district: 'Dokki',
    address: '14 Al-Mesaha Square, Dokki',
    phone: '+20 2 3761 0000',
    branches: [
      { id: 'br_dokki', name: 'Dokki Main Branch', nameAr: 'فرع الدقي الرئيسي' },
      { id: 'br_mohandessin', name: 'Mohandessin Branch', nameAr: 'فرع المهندسين' }
    ],
    onlinePaymentsEnabled: true,
    paymentMethods: ['card', 'wallet', 'cash'],
    subscriptionStatus: 'active',
    subscriptionPlan: 'Enterprise Tier',
    isFoundingCenter: true,
  },
  {
    id: 'center_future',
    name: 'Future Academy Center',
    nameAr: 'سنتر أكاديمية المستقبل',
    code: 'FUT-02',
    city: 'Cairo',
    district: 'Nasr City',
    address: '88 Makram Ebeid St., Nasr City',
    phone: '+20 2 2270 5555',
    branches: [
      { id: 'br_nasrcity', name: 'Nasr City Branch', nameAr: 'فرع مدينة نصر' }
    ],
    onlinePaymentsEnabled: false,
    paymentMethods: ['cash'],
    subscriptionStatus: 'active',
    subscriptionPlan: 'Standard Growth',
    isFoundingCenter: false,
  },
  {
    id: 'center_elite',
    name: 'Elite Education Center',
    nameAr: 'سنتر النخبة التعليمي',
    code: 'ELT-03',
    city: 'Cairo',
    district: 'Maadi',
    address: '22 Road 9, Maadi',
    phone: '+20 2 2380 9999',
    branches: [
      { id: 'br_maadi', name: 'Maadi Branch', nameAr: 'فرع المعادي' }
    ],
    onlinePaymentsEnabled: true,
    paymentMethods: ['card', 'wallet', 'cash'],
    subscriptionStatus: 'active',
    subscriptionPlan: 'Professional',
    isFoundingCenter: true,
  }
];

export const INITIAL_TEACHERS = [
  {
    userId: 'user_teacher_1',
    name: 'Mr. Ahmed Hassan',
    nameAr: 'أ. أحمد حسن',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'Senior Physics Specialist',
    subjects: ['Physics', 'Advanced Mechanics'],
    subjectsAr: ['فيزياء', 'ميكانيكا متقدمة'],
    grades: ['Grade 10', 'Grade 11', 'Grade 12'],
    rating: 4.74,
    ratingCount: 286,
    ratingDistribution: { 5: 75, 4: 18, 3: 5, 2: 1, 1: 1 },
    experienceYears: 14,
    centerIds: ['center_kayedu', 'center_future', 'center_elite'],
    centersNames: ['KAYEDU Demo Center', 'Future Academy Center'],
    bio: '14+ years coaching high school physics. Expert in simplifying Newton mechanics, thermodynamics, and electricity with high Thanweya Amma success rates.',
    bioAr: 'أكثر من 14 عاماً في تدريس الفيزياء للثانوية العامة، متخصص في تبسيط الكهربية والميكانيكا والفيزياء الحديثة بأعلى نسب تفوق.',
    verified: true,
    onlineAvailable: true,
  },
  {
    userId: 'user_teacher_2',
    name: 'Mr. Karim Mostafa',
    nameAr: 'أ. كريم مصطفى',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    title: 'Physics & Applied Science Educator',
    subjects: ['Physics'],
    subjectsAr: ['فيزياء'],
    grades: ['Grade 11', 'Grade 12'],
    rating: 4.70,
    ratingCount: 194,
    ratingDistribution: { 5: 71, 4: 21, 3: 6, 2: 1, 1: 1 },
    experienceYears: 10,
    centerIds: ['center_kayedu', 'center_future'],
    centersNames: ['KAYEDU Demo Center', 'Future Academy Center'],
    bio: 'Interactive experimental physics instructor focusing on conceptual clarity and exam solving strategies.',
    bioAr: 'معلم فيزياء يعتمد على التطبيقات العملية وحل الأسئلة المتقدمة وفق منظومة الامتحانات الحديثة.',
    verified: true,
    onlineAvailable: false,
  },
  {
    userId: 'user_teacher_3',
    name: 'Dr. Mona El-Sayed',
    nameAr: 'د. منى السيد',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: 'Ph.D. Chemistry Consultant',
    subjects: ['Chemistry'],
    subjectsAr: ['كيمياء'],
    grades: ['Grade 10', 'Grade 11'],
    rating: 4.88,
    ratingCount: 342,
    ratingDistribution: { 5: 88, 4: 9, 3: 2, 2: 1, 1: 0 },
    experienceYears: 16,
    centerIds: ['center_elite', 'center_kayedu'],
    centersNames: ['Elite Education Center', 'KAYEDU Demo Center'],
    bio: 'Former university faculty member specializing in Organic Chemistry and analytical stoichiometry.',
    bioAr: 'دكتوراه في الكيمياء، متخصصة في الكيمياء العضوية والتحليلية للمرحلة الثانوية.',
    verified: true,
    onlineAvailable: true,
  },
  {
    userId: 'user_teacher_4',
    name: 'Mr. Tarek Mahmoud',
    nameAr: 'أ. طارق محمود',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    title: 'Pure & Applied Mathematics Master',
    subjects: ['Mathematics', 'Calculus', 'Algebra'],
    subjectsAr: ['رياضيات', 'تفاضل وتكامل', 'جبر'],
    grades: ['Grade 11', 'Grade 12'],
    rating: 4.65,
    ratingCount: 150,
    ratingDistribution: { 5: 68, 4: 22, 3: 8, 2: 1, 1: 1 },
    experienceYears: 12,
    centerIds: ['center_future'],
    centersNames: ['Future Academy Center'],
    bio: 'Math olympiad mentor specializing in calculus, vectors and complex numbers.',
    bioAr: 'خبير الرياضيات البحتة والتطبيقية، مدرب أولمبياد الرياضيات.',
    verified: true,
    onlineAvailable: true,
  }
];

export const INITIAL_SESSIONS: Session[] = [
  {
    id: 'sess_phy_today',
    centerId: 'center_kayedu',
    centerName: 'KAYEDU Demo Center',
    centerNameAr: 'سنتر كاي إديو النموذجي',
    branchName: 'Dokki Main Branch',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    teacherNameAr: 'أ. أحمد حسن',
    teacherAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    subject: 'Physics',
    subjectAr: 'فيزياء',
    grade: 'Grade 11',
    groupName: 'Group A — Mechanics & Waves',
    room: 'Room 4',
    date: '2026-09-08',
    startTime: '18:00',
    endTime: '20:00',
    priceEgp: 200,
    isOnline: false,
    capacity: 35,
    enrolledCount: 32,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_chem_today',
    centerId: 'center_kayedu',
    centerName: 'KAYEDU Demo Center',
    centerNameAr: 'سنتر كاي إديو النموذجي',
    branchName: 'Dokki Main Branch',
    teacherId: 'user_teacher_3',
    teacherName: 'Dr. Mona El-Sayed',
    teacherNameAr: 'د. منى السيد',
    teacherAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    subject: 'Chemistry',
    subjectAr: 'كيمياء',
    grade: 'Grade 11',
    groupName: 'Group B — Ionic Equilibrium',
    room: 'Hall 1',
    date: '2026-09-08',
    startTime: '15:30',
    endTime: '17:30',
    priceEgp: 220,
    isOnline: false,
    capacity: 40,
    enrolledCount: 38,
    status: 'COMPLETED',
  },
  {
    id: 'sess_math_tomorrow',
    centerId: 'center_future',
    centerName: 'Future Academy Center',
    centerNameAr: 'سنتر أكاديمية المستقبل',
    branchName: 'Nasr City Branch',
    teacherId: 'user_teacher_4',
    teacherName: 'Mr. Tarek Mahmoud',
    teacherNameAr: 'أ. طارق محمود',
    teacherAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    subject: 'Mathematics',
    subjectAr: 'رياضيات',
    grade: 'Grade 11',
    groupName: 'Group C — Calculus Derivatives',
    room: 'Room 12',
    date: '2026-09-09',
    startTime: '17:00',
    endTime: '19:00',
    priceEgp: 180,
    isOnline: false,
    capacity: 30,
    enrolledCount: 30,
    status: 'SCHEDULED',
  },
  {
    id: 'sess_phy_online',
    centerId: 'center_kayedu',
    centerName: 'KAYEDU Demo Center',
    centerNameAr: 'سنتر كاي إديو النموذجي',
    branchName: 'Online Virtual Hall',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    teacherNameAr: 'أ. أحمد حسن',
    teacherAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    subject: 'Physics',
    subjectAr: 'فيزياء',
    grade: 'Grade 11',
    groupName: 'Weekly Problem Solving Marathon',
    room: 'Zoom Room Alpha',
    date: '2026-09-10',
    startTime: '20:00',
    endTime: '21:30',
    priceEgp: 150,
    isOnline: true,
    onlineMeetingUrl: 'https://kayedu.live/room/phy-11-marathon',
    capacity: 100,
    enrolledCount: 78,
    status: 'SCHEDULED',
  }
];

export const INITIAL_ENROLLMENTS: StudentSessionEnrollment[] = [
  {
    id: 'enr_1',
    sessionId: 'sess_phy_today',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    studentCode: 'ST-001245',
    studentAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    paymentStatus: 'PENDING', // starts pending for journey 1 test!
    reservationStatus: 'CONFIRMED',
  },
  {
    id: 'enr_2',
    sessionId: 'sess_phy_today',
    studentId: 'user_student_sara',
    studentName: 'Sara Ali',
    studentCode: 'ST-001246',
    studentAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    paymentStatus: 'PAID',
    paymentMethod: 'online_card',
    paidAmount: 200,
    paidAt: '2026-09-08 14:20',
    receiptNumber: 'REC-20260908-019',
    attendanceStatus: 'PRESENT',
    attendanceTime: '17:52',
    reservationStatus: 'CONFIRMED',
  },
  {
    id: 'enr_3',
    sessionId: 'sess_phy_today',
    studentId: 'user_student_omar',
    studentName: 'Omar Khaled',
    studentCode: 'ST-001247',
    studentAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    paymentStatus: 'PENDING', // For Journey 3 (unpaid student cash collection demo!)
    reservationStatus: 'CONFIRMED',
  }
];

export const INITIAL_HOMEWORK: Homework[] = [
  {
    id: 'hw_phy_1',
    sessionId: 'sess_phy_today',
    teacherId: 'user_teacher_1',
    centerId: 'center_kayedu',
    subject: 'Physics',
    grade: 'Grade 11',
    title: 'Harmonic Motion & Wave Interference Problem Set',
    titleAr: 'مسائل الحركة التوافقية البسيطة وتداخل الأمواج',
    instructions: 'Complete all 5 problems showing calculation steps. Pay attention to SI units conversions.',
    dueDate: '2026-09-12 23:59',
    assignedDate: '2026-09-07',
    status: 'PUBLISHED',
    questionsCount: 5,
    questions: [
      {
        id: 'q1',
        type: 'mcq',
        prompt: 'If the frequency of a vibrating pendulum is doubled, its periodic time will:',
        choices: ['Double', 'Halve', 'Remain unchanged', 'Quadruple'],
        correctAnswer: 'Halve',
        points: 2
      },
      {
        id: 'q2',
        type: 'true_false',
        prompt: 'Electromagnetic waves require a material medium to propagate through space.',
        choices: ['True', 'False'],
        correctAnswer: 'False',
        points: 2
      },
      {
        id: 'q3',
        type: 'short_answer',
        prompt: 'State the relationship between wave speed (v), frequency (f), and wavelength (lambda).',
        correctAnswer: 'v = f * lambda',
        points: 3
      }
    ]
  },
  {
    id: 'hw_chem_1',
    sessionId: 'sess_chem_today',
    teacherId: 'user_teacher_3',
    centerId: 'center_kayedu',
    subject: 'Chemistry',
    grade: 'Grade 11',
    title: 'Le Chatelier Principle Applications',
    titleAr: 'تطبيقات قاعدة لوشاتيليه في الاتزان الكيميائي',
    instructions: 'Analyze the reaction quotient under temperature and pressure shifts.',
    dueDate: '2026-09-14 20:00',
    assignedDate: '2026-09-08',
    status: 'PUBLISHED',
    questionsCount: 4,
  }
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam_phy_mid',
    centerId: 'center_kayedu',
    teacherId: 'user_teacher_1',
    subject: 'Physics',
    grade: 'Grade 11',
    title: 'Monthly Physics Assessment — Mechanics',
    durationMinutes: 45,
    date: '2026-09-15',
    startTime: '18:00',
    totalPoints: 30,
    status: 'OPEN',
    questions: [
      {
        id: 'eq1',
        questionNumber: 1,
        type: 'mcq',
        prompt: 'A body moves in circular motion with constant speed. Which of the following is correct?',
        choices: [
          'Its acceleration is zero',
          'Its velocity vector is constant',
          'Centripetal acceleration is directed toward the circle center',
          'Linear speed is proportional to period'
        ],
        correctAnswer: 'Centripetal acceleration is directed toward the circle center',
        points: 5
      },
      {
        id: 'eq2',
        questionNumber: 2,
        type: 'true_false',
        prompt: 'Gravitational acceleration remains identical regardless of altitude above Earth.',
        choices: ['True', 'False'],
        correctAnswer: 'False',
        points: 5
      },
      {
        id: 'eq3',
        questionNumber: 3,
        type: 'mcq',
        prompt: 'What happens to the kinetic energy of a car if its speed is tripled?',
        choices: ['Triples (3x)', 'Increases to 6x', 'Increases to 9x', 'Remains the same'],
        correctAnswer: 'Increases to 9x',
        points: 5
      }
    ]
  }
];

export const INITIAL_MATERIALS: MaterialItem[] = [
  {
    id: 'mat_1',
    title: 'Physics Chapter 1 Summary — Vectors & Motion Notes (PDF)',
    subject: 'Physics',
    grade: 'Grade 11',
    teacherName: 'Mr. Ahmed Hassan',
    type: 'pdf',
    fileSize: '4.2 MB',
    url: '#',
    date: '2026-09-05'
  },
  {
    id: 'mat_2',
    title: 'Comprehensive Organic Chemistry Formulas & Functional Groups',
    subject: 'Chemistry',
    grade: 'Grade 11',
    teacherName: 'Dr. Mona El-Sayed',
    type: 'pdf',
    fileSize: '3.1 MB',
    url: '#',
    date: '2026-09-06'
  },
  {
    id: 'mat_3',
    title: 'Interactive 3D Wave Interference Simulation Link',
    subject: 'Physics',
    grade: 'Grade 11',
    teacherName: 'Mr. Ahmed Hassan',
    type: 'link',
    url: 'https://phet.colorado.edu/en/simulations/wave-interference',
    date: '2026-09-07'
  }
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp_1',
    centerId: 'center_kayedu',
    name: 'Nouran Samir',
    nameAr: 'نوران سمير',
    phone: '+20 122 333 4455',
    role: 'Receptionist',
    branchName: 'Dokki Main Branch',
    status: 'active',
    compensationModel: 'HYBRID',
    baseSalaryEgp: 6500,
    sessionPercentage: 2,
    eligibleSessionsThisMonth: 42,
    startDate: '2024-06-15',
  },
  {
    id: 'emp_2',
    centerId: 'center_kayedu',
    name: 'Hassan Sherif',
    nameAr: 'حسن شريف',
    phone: '+20 109 888 7766',
    role: 'Floor Supervisor',
    branchName: 'Dokki Main Branch',
    status: 'active',
    compensationModel: 'FIXED_PER_SESSION',
    baseSalaryEgp: 0,
    perSessionRateEgp: 90,
    eligibleSessionsThisMonth: 58,
    startDate: '2024-09-01',
  },
  {
    id: 'emp_3',
    centerId: 'center_kayedu',
    name: 'Marwa Zaki',
    nameAr: 'مروة زكي',
    phone: '+20 115 444 3322',
    role: 'Accountant',
    branchName: 'Dokki Main Branch',
    status: 'active',
    compensationModel: 'FIXED_SALARY',
    baseSalaryEgp: 8500,
    eligibleSessionsThisMonth: 0,
    startDate: '2024-03-01',
  }
];

export const INITIAL_PAYROLL: PayrollRecord[] = [
  {
    id: 'pay_01',
    centerId: 'center_kayedu',
    employeeId: 'emp_1',
    employeeName: 'Nouran Samir',
    role: 'Receptionist',
    period: '2026-08',
    baseSalaryEgp: 6500,
    sessionEarningsEgp: 1680,
    bonusEgp: 500,
    overtimeEgp: 350,
    deductionsEgp: 0,
    netPayEgp: 9030,
    status: 'APPROVED',
  },
  {
    id: 'pay_02',
    centerId: 'center_kayedu',
    employeeId: 'emp_2',
    employeeName: 'Hassan Sherif',
    role: 'Floor Supervisor',
    period: '2026-08',
    baseSalaryEgp: 0,
    sessionEarningsEgp: 5220,
    bonusEgp: 300,
    overtimeEgp: 0,
    deductionsEgp: 150,
    netPayEgp: 5370,
    status: 'REVIEWED',
  }
];

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: 'exp_1',
    centerId: 'center_kayedu',
    category: 'Rent',
    amountEgp: 35000,
    date: '2026-09-01',
    branch: 'Dokki Main Branch',
    description: 'Monthly facility commercial lease — Dokki 14 Al-Mesaha',
    paymentMethod: 'Bank Transfer',
    createdBy: 'Eng. Mahmoud El-Kady',
  },
  {
    id: 'exp_2',
    centerId: 'center_kayedu',
    category: 'Electricity',
    amountEgp: 6400,
    date: '2026-09-03',
    branch: 'Dokki Main Branch',
    description: 'Electricity & Air Conditioning utility bill for August',
    paymentMethod: 'Fawry Business',
    createdBy: 'Marwa Zaki',
  },
  {
    id: 'exp_3',
    centerId: 'center_kayedu',
    category: 'Internet',
    amountEgp: 2200,
    date: '2026-09-04',
    branch: 'Dokki Main Branch',
    description: 'Fiber internet 200Mbps dedicated connection',
    paymentMethod: 'Credit Card',
    createdBy: 'Marwa Zaki',
  },
  {
    id: 'exp_4',
    centerId: 'center_kayedu',
    category: 'Supplies',
    amountEgp: 4800,
    date: '2026-09-05',
    branch: 'Dokki Main Branch',
    description: 'Photocopy paper reams & white board markers for halls',
    paymentMethod: 'Cash Voucher',
    createdBy: 'Nouran Samir',
  }
];

export const INITIAL_TEACHER_SETTLEMENTS: TeacherSettlement[] = [
  {
    id: 'settle_1',
    centerId: 'center_kayedu',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    subject: 'Physics',
    period: '2026-08',
    sessionsCount: 16,
    attendedStudentsCount: 512,
    totalRevenueEgp: 102400,
    calculationRule: 'percentage_80',
    teacherShareEgp: 81920,
    centerShareEgp: 20480,
    adjustmentsEgp: 0,
    paidAmountEgp: 81920,
    status: 'PAID',
    paidAt: '2026-09-02',
  },
  {
    id: 'settle_2',
    centerId: 'center_kayedu',
    teacherId: 'user_teacher_3',
    teacherName: 'Dr. Mona El-Sayed',
    subject: 'Chemistry',
    period: '2026-08',
    sessionsCount: 14,
    attendedStudentsCount: 440,
    totalRevenueEgp: 96800,
    calculationRule: 'percentage_75',
    teacherShareEgp: 72600,
    centerShareEgp: 24200,
    adjustmentsEgp: -600,
    paidAmountEgp: 0,
    status: 'REVIEWED',
  }
];

export const INITIAL_TEACHER_NOTES: TeacherNote[] = [
  {
    id: 'note_1',
    teacherId: 'user_teacher_1',
    teacherName: 'Mr. Ahmed Hassan',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    type: 'Academic',
    visibility: 'parent_and_student',
    content: 'Demonstrated outstanding grasp of Newton third law applications in problem set 3. Recommended for Thanweya Amma honor group.',
    date: '2026-09-06',
  },
  {
    id: 'note_2',
    teacherId: 'user_teacher_3',
    teacherName: 'Dr. Mona El-Sayed',
    studentId: 'user_student_1',
    studentName: 'Ahmed Mohamed',
    type: 'Follow-up',
    visibility: 'parent_only',
    content: 'Missed chemistry lab worksheet review on Tuesday. Please ensure he revises ionic reactions before the upcoming quiz.',
    date: '2026-09-07',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'user_student_1',
    type: 'class_reminder',
    title: 'Physics Class Today at 6:00 PM',
    titleAr: 'تذكير: حصة الفيزياء اليوم الساعة 6:00 مساءً',
    message: 'Mr. Ahmed Hassan in Room 4, Dokki Main Branch. Have your attendance QR ready.',
    messageAr: 'مع أ. أحمد حسن في القاعة 4، فرع الدقي. جهز رمز QR للحضور عند الاستقبال.',
    timestamp: '10 mins ago',
    read: false,
  },
  {
    id: 'notif_2',
    userId: 'user_student_1',
    type: 'homework',
    title: 'New Physics Homework Assigned',
    titleAr: 'واجب جديد: مسائل الحركة التوافقية',
    message: 'Due date: Saturday Sep 12, 11:59 PM.',
    messageAr: 'موعد التسليم الأخير: السبت 12 سبتمبر الساعة 11:59 مساءً.',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: 'notif_3',
    userId: 'user_student_1',
    type: 'exam',
    title: 'Assessment Result Published',
    titleAr: 'تم إعلان نتيجة الاختبار الأسبوعي',
    message: 'You scored 28/30 (93.3%) in Wave Mechanics.',
    messageAr: 'حصلت على 28 من 30 (93.3%) في ميكانيكا الموجات.',
    timestamp: 'Yesterday',
    read: true,
  }
];
